package com.stefanini.model;
// Generated 07/11/2016 12:12:48 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "hackathon")
public class Modelo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idModelo", unique = true, nullable = false)
	private Integer idModelo;
		
	@OneToOne
	@JoinColumn(name="idCategoria")
	private Categoria categoria;
	
	@Column(name = "descricaoModelo", length = 50)
	private String descricaoModelo;

	public Modelo() {
	}

	

	public Modelo(Integer idModelo, Categoria categoria, String descricaoModelo) {
		super();
		this.idModelo = idModelo;
		this.categoria = categoria;
		this.descricaoModelo = descricaoModelo;
	}




	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}
	
	
	public String getDescricaoModelo() {
		return this.descricaoModelo;
	}
	
	public void setDescricaoModelo(String descricaoModelo) {
		this.descricaoModelo = descricaoModelo;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	


	

	
}
