package com.stefanini.model;
// Generated 07/11/2016 12:12:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TelefonesId generated by hbm2java
 */
@Entity
@Table(name = "telefone", catalog = "hackathon")
public class Telefone implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idTelefone;
	
	@Column(name = "numero", length = 100)
	private String numero;
	
	@Column(name = "ddd", length = 100)
	private String ddd;
	
	@OneToOne
	@JoinColumn(name ="idProprietario")
	private Proprietario proprietario;
	
	@OneToOne
	@JoinColumn(name ="idTipoTelefone")
	private Tipotelefone tipotelefone;
	

	public Telefone() {
	}

	public Telefone(String numero, String ddd) {
		this.numero = numero;
		this.ddd = ddd;
	}

	
	public Tipotelefone getTipotelefone() {
		return tipotelefone;
	}

	public void setTipotelefone(Tipotelefone tipotelefone) {
		this.tipotelefone = tipotelefone;
	}



	public Proprietario getProprietario() {
		return proprietario;
	}

	public void setProprietario(Proprietario proprietario) {
			this.proprietario = proprietario;
	}

	public Integer getIdTelefone() {
		return idTelefone;
	}

	public void setIdTelefone(Integer idTelefone) {
		this.idTelefone = idTelefone;
	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getDdd() {
		return ddd;
	}

	public void setDdd(String ddd) {
		this.ddd = ddd;
	}
	
	
	
	
	
	
}
