package com.stefanini.model;
// Generated 07/11/2016 12:12:48 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Veiculos generated by hbm2java
 */
@Entity
@Table(name = "veiculo", catalog = "hackathon")
public class Veiculo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVeiculo", unique = true, nullable = false)
	private Integer idVeiculo;
	
	@Column(name = "placa", length = 50)
	private String placa;
	
	@Column(name = "idProprietario", nullable = false)
	private int idProprietario;
	
	@Column(name = "idModelo", nullable = false)
	private int idModelo;
	
	@Column(name = "uf", nullable = false, length = 2)
	private String uf;

	public Veiculo() {
	}

	public Veiculo(String placa, int idProprietario, int idModelo, String uf) {
		this.placa = placa;
		this.idProprietario = idProprietario;
		this.idModelo = idModelo;
		this.uf = uf;
	}

	
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	
	public int getIdProprietario() {
		return idProprietario;
	}

	public void setIdProprietario(int idProprietario) {
		this.idProprietario = idProprietario;
	}


	public int getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(int idModelo) {
		this.idModelo = idModelo;
	}

	
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public Integer getIdVeiculo() {
		return idVeiculo;
	}

	public void setIdVeiculo(Integer idVeiculo) {
		this.idVeiculo = idVeiculo;
	}
	
	

}
